/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paneles;

import Controlador.ControladorPrincipal;
import Modelo.Conexion;
import com.sun.org.apache.xerces.internal.impl.xs.opti.DefaultDocument;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARIANA
 */
public class PanelRegistroProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form PanelRegistroProducto1
     */
    Conexion conexion;
    DefaultTableModel model;
    int filas = 0;
    
    public PanelRegistroProducto() {
        initComponents();
        
         Calendar c2 = new GregorianCalendar();
        jdcFechaRegistroProducto.setCalendar(c2);
        jdcFechaRegistroProducto.setEnabled(false);
        
        
        
        this.jcbCategoriaProducto.removeAllItems();
        this.cbxProveedor.removeAllItems();
            
            conexion = new Conexion();
            java.sql.Connection accesoBD = null;
            Statement ps = null;
            
        try{
            //conexion = new Conexion();
            
            accesoBD = conexion.getConnection();
            ps = (Statement) accesoBD.createStatement();
            //Statement sent = conexion.createStatement(); 
           ResultSet rs = ps.executeQuery("SELECT * FROM categoria");
            
               
            while(rs.next()){
            this.jcbCategoriaProducto.addItem(rs.getString("nombreNuevaCategoria"));
            }  
        }catch(Exception ex){
        Logger.getLogger(ControladorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try {
            accesoBD = conexion.getConnection();
            ps = (Statement) accesoBD.createStatement();
            //Statement sent = conexion.createStatement(); 
           ResultSet rs = ps.executeQuery("SELECT * FROM proveedor");
            
            while(rs.next()){
            this.cbxProveedor.addItem(rs.getString("nombreProveedor"));
            } 
            
        } catch (SQLException ex) {
            Logger.getLogger(PanelRegistroProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfCodigoProducto = new javax.swing.JTextField();
        jtfDescripcionProducto = new javax.swing.JTextField();
        jcbCategoriaProducto = new javax.swing.JComboBox();
        jtfStock = new javax.swing.JTextField();
        jtfPuntoPedido = new javax.swing.JTextField();
        jtfMarcaProducto = new javax.swing.JTextField();
        jdcFechaRegistroProducto = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        cbxProveedor = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jtfResponsable = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePrecios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Registro de Producto");
        setToolTipText("");
        getContentPane().setLayout(null);

        jLabel9.setText("DESCRIPCION DE PRODUCTO");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 11, 524, 18);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setText("Código:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 16, 37, 14);

        jLabel3.setText("Descripción:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(12, 76, 58, 14);

        jLabel4.setText("Marca:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(12, 115, 33, 14);

        jLabel5.setText("Fecha de Registro:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(289, 16, 91, 14);

        jLabel6.setText("Categoria:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(12, 166, 51, 14);

        jLabel7.setText("Stock Actual:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(297, 116, 63, 14);

        jLabel8.setText("Punto de Pedido:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(12, 229, 82, 14);

        jtfCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoProductoActionPerformed(evt);
            }
        });
        jtfCodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCodigoProductoKeyTyped(evt);
            }
        });
        jPanel1.add(jtfCodigoProducto);
        jtfCodigoProducto.setBounds(132, 13, 126, 20);
        jPanel1.add(jtfDescripcionProducto);
        jtfDescripcionProducto.setBounds(132, 75, 380, 20);

        jcbCategoriaProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Snack", "Bebidas", "Galletas" }));
        jPanel1.add(jcbCategoriaProducto);
        jcbCategoriaProducto.setBounds(132, 151, 126, 20);

        jtfStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfStockActionPerformed(evt);
            }
        });
        jtfStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfStockKeyTyped(evt);
            }
        });
        jPanel1.add(jtfStock);
        jtfStock.setBounds(408, 105, 104, 20);

        jtfPuntoPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPuntoPedidoKeyTyped(evt);
            }
        });
        jPanel1.add(jtfPuntoPedido);
        jtfPuntoPedido.setBounds(370, 200, 105, 20);

        jtfMarcaProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfMarcaProductoKeyTyped(evt);
            }
        });
        jPanel1.add(jtfMarcaProducto);
        jtfMarcaProducto.setBounds(132, 113, 126, 20);
        jPanel1.add(jdcFechaRegistroProducto);
        jdcFechaRegistroProducto.setBounds(390, 13, 122, 20);

        jLabel12.setText("Proveedor:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(297, 151, 54, 14);

        cbxProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Item 1", "Item 2", "Item 3" }));
        jPanel1.add(cbxProveedor);
        cbxProveedor.setBounds(390, 151, 122, 20);

        jLabel13.setText("Responsable:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(12, 246, 65, 20);

        jtfResponsable.setEditable(false);
        jPanel1.add(jtfResponsable);
        jtfResponsable.setBounds(132, 246, 380, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 35, 540, 310);

        jLabel10.setText("PRECIOS");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(18, 366, 205, 26);

        tablePrecios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Unidad", "Venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePrecios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(18, 398, 256, 144);

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(233, 366, 41, 26);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Lote"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(292, 398, 257, 144);

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(508, 369, 41, 23);

        jLabel14.setText("VENCIMIENTOS");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel14);
        jLabel14.setBounds(292, 366, 104, 26);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(406, 369, 87, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoProductoActionPerformed

    private void jtfCodigoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoProductoKeyTyped
        
        char c = evt.getKeyChar();
        int limite = 13;
        int longitudCadena = jtfCodigoProducto.getText().length();
        if (!Character.isDigit(c)|| longitudCadena == limite) {
            evt.consume();//no permite digitar
        }
    }//GEN-LAST:event_jtfCodigoProductoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        model = (DefaultTableModel) this.tablePrecios.getModel();
        model.addRow(new Object[filas]);
        filas++;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfMarcaProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMarcaProductoKeyTyped
       char c = evt.getKeyChar();
        String nomProd = jtfMarcaProducto.getText();
        if (Character.isLetter(c) || c == KeyEvent.VK_SPACE) {
             if(nomProd.length() == 40){
                evt.consume();
            }
            //Permite ingreso
            if (Character.isLowerCase(c)) {
                String cadena = (""+c).toUpperCase();
                c = cadena.charAt(0);
                evt.setKeyChar(c);
            }
        }else{
            
            evt.consume();
        }
    }//GEN-LAST:event_jtfMarcaProductoKeyTyped

    private void jtfStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfStockKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();//no permite digitar
        }
    }//GEN-LAST:event_jtfStockKeyTyped

    private void jtfPuntoPedidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPuntoPedidoKeyTyped
       char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();//no permite digitar
        }
    }//GEN-LAST:event_jtfPuntoPedidoKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtfStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfStockActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cbxProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JComboBox jcbCategoriaProducto;
    public com.toedter.calendar.JDateChooser jdcFechaRegistroProducto;
    public javax.swing.JTextField jtfCodigoProducto;
    public javax.swing.JTextField jtfDescripcionProducto;
    public javax.swing.JTextField jtfMarcaProducto;
    public javax.swing.JTextField jtfPuntoPedido;
    public javax.swing.JTextField jtfResponsable;
    public javax.swing.JTextField jtfStock;
    public javax.swing.JTable tablePrecios;
    // End of variables declaration//GEN-END:variables
}
